### ISSUE TITLE
Unrecognised distance unit in v3.0.0 beta 1

### ISSUE THREAD

**Issue by Djelibeybi** [msp1974/homeassistant-jlrincontrol#113]
Hey folks, just upgraded to the v3.0.0 beta 1 release and I'm getting the following error in my logs:

```log
2024-02-02 03:54:47.858 ERROR (MainThread) [homeassistant.components.sensor] jlrincontrol: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 93, in _get_from_to_ratio
    return unit_conversion[from_unit], unit_conversion[to_unit]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: <UnitOfVolume.LITERS: 'L'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/jlrincontrol/entity.py", line 79, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/sensor.py", line 322, in extra_state_attributes
    unit_conversion.DistanceConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 73, in convert
    return cls.converter_factory(from_unit, to_unit)(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 83, in converter_factory
    from_ratio, to_ratio = cls._get_from_to_ratio(from_unit, to_unit)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 95, in _get_from_to_ratio
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: L is not a recognized distance unit.
```

This is for a Land Rover Discovery Sport HSE (2020).

**Comment by Djelibeybi** [comment]
Diagnostic download was uploaded to #114

**Comment by msp1974** [comment]
Yes, this is a stupid typo on my part for a value my car doesn't supply.  If you want to temp fix until I release beta2 then line 320 of sensor.py should be:
```
if key == "exhaust fluid fill":
  attrs[key.title()] = int(
      unit_conversion.VolumeConverter.convert(
          int(status.get(value).title()),
          UnitOfVolume.LITERS,
          self._units,
      )
  )
```

and not DistanceConverter as I had put.

**Comment by Djelibeybi** [comment]
I had to disable the entire block. Just replacing that code got me a similar but different error. 

Also, my values for some of these keys are strings, i.e. "normal" and not integers, so the `int()` fails too.

**Comment by msp1974** [comment]
Yes there was another error.  Just released beta2 which should resolve if you can give that a go.  Thx

> Also, my values for some of these keys are strings, i.e. "normal" and not integers, so the int() fails too.

Looking in your diag file, none of those keys were non numeric.

**Comment by Djelibeybi** [comment]
I'm getting this error with beta 2:

```log
2024-02-03 21:29:46.825 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform jlrincontrol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 93, in _get_from_to_ratio
    return unit_conversion[from_unit], unit_conversion[to_unit]
                                       ~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/sensor.py", line 219, in extra_state_attributes
    unit_conversion.PressureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 73, in convert
    return cls.converter_factory(from_unit, to_unit)(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 83, in converter_factory
    from_ratio, to_ratio = cls._get_from_to_ratio(from_unit, to_unit)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 95, in _get_from_to_ratio
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: None is not a recognized pressure unit.
2024-02-03 21:29:46.837 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up jlrincontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 93, in _get_from_to_ratio
    return unit_conversion[from_unit], unit_conversion[to_unit]
                                       ~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1282, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/sensor.py", line 219, in extra_state_attributes
    unit_conversion.PressureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 73, in convert
    return cls.converter_factory(from_unit, to_unit)(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 83, in converter_factory
    from_ratio, to_ratio = cls._get_from_to_ratio(from_unit, to_unit)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 95, in _get_from_to_ratio
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: None is not a recognized pressure unit.
```

**Comment by msp1974** [comment]
Yes, this is a known issue #117  (well as of yesterday! 😀).  If you change the pressure units in the config options and save, it will fix it.  This is resolved for the next beta release which will be today or tomorrow.

**Comment by Djelibeybi** [comment]
I'm getting this now:

```
2024-02-03 23:11:36.567 ERROR (MainThread) [homeassistant.components.switch] jlrincontrol: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/jlrincontrol/entity.py", line 79, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/sensor.py", line 324, in extra_state_attributes
    self.coordinator.user.user_preferences.volume,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserPreferenceUnits' object has no attribute 'volume'
```

I've tried changing the pressure units several times and it happens regardless of which option I pick.

**Comment by msp1974** [comment]
ARGG!! Def need to find better ways to test this.  That should be...
```
self.coordinator.user.user_preferences.fuel
```
in line 324 of sensor.py.

I will get this right, I promise! :-)

**Comment by msp1974** [comment]
I am guessing this is resolved?

**Comment by Djelibeybi** [comment]
Yep, sorry. Have been offline for medical reasons for a while.
