### ISSUE TITLE
DS Hybrid battery state no longer shown in 3.0.0 beta 1

### ISSUE THREAD

**Issue by Liam-Whiteside** [msp1974/homeassistant-jlrincontrol#115]
sensor.ds_hybrid_battery is no longer available after updating to 3.0.0beta1.

Also, if I go to the integration and click on the "configure" option, if I click submit, I get an error "Unknown error occurred"

**Comment by msp1974** [comment]
Can you provide diag output.  thx

**Comment by msp1974** [comment]
Can you also see if there is a more explanatory error in the logs

**Comment by Liam-Whiteside** [comment]
What diag output is going to he helpful, and where can I look for logs? (my home assistant core logs are quite noisy, but I couldn't see anything about this integration.)

**Comment by msp1974** [comment]
On the 3 dots menu next to configure is option for download diagnostics - this is the one I want.

Also, if it gave an unknown error then there is likely some error in the core log.  Maybe try it again and look near the top.

**Comment by Liam-Whiteside** [comment]
[config_entry-jlrincontrol-3a5a766573d9cc96491cf9b72151bb8c.json.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/14141321/config_entry-jlrincontrol-3a5a766573d9cc96491cf9b72151bb8c.json.txt)

I'm not sure if this is relevant at all
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 13:46:18 (5 occurrences)
Last logged: 14:24:56

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 234, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/config_flow.py", line 162, in async_step_user
    CONF_USE_CHINA_SERVERS: self.config_entry.data[
                            ^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'use_china_servers'
```

**Comment by msp1974** [comment]
This is perfect.  Will issue a beta2 shortly that will fix this and some other issues.

**Comment by msp1974** [comment]
ok, if you can download and give beta2 a try to see if these issues are fixed.  thx

**Comment by Liam-Whiteside** [comment]
beta2 installed and appears to have fixed both of those issues. Thanks
