### ISSUE TITLE
real-time positioning updates

### ISSUE THREAD

**Issue by ghost** [msp1974/homeassistant-jlrincontrol#17]

**Comment by msp1974** [comment]
Stefan,  you are right, there is journey tracking which will list the history of journeys made and you can query a single journey and get all the waypoints and info as you say.

I'm just not sure how to use this in HA.  You cannot 'import' data afaik into a device tracker and only provide gps coordinates on a realtime basis (ie you cannot add a historic date and time).

If anyone else knows how we can use this in HA, more than happy to work through doing it.

**Comment by msp1974** [comment]
Stefan,  I have added a new sensor to this integration to show the last trip made.  It doesn't however show a map or route.  See what you think about it.

PS In the dev branch.

**Comment by stefanv84** [comment]
Hi, thanks for the effort but unfortunately I'm getting an error with this dev branch;

2020-04-26 22:17:59 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up jlrincontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/jlrincontrol/sensor.py", line 340, in device_state_attributes
    attrs["eco_score"] = t.get("totalEcoScore").get("score")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by msp1974** [comment]
update from dev again.  Should work now.

**Comment by stefanv84** [comment]
Both the last trip and geocoded location work well now! Have to think about if and how the last trip can be logged. Thanks again, will be closing this issue.
